version: 0.0
os: linux
files:
  - source: /webroot/
    destination: /var/www/html/

hooks:
  ApplicationStop:
    - location: scripts/stop_httpd
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_httpd
      timeout: 300
      runas: root
    
